Testing verdaccio.

diff --git a/.github/workflows/release-test.yml b/.github/workflows/release-test.yml
--- a/.github/workflows/release-test.yml
+++ b/.github/workflows/release-test.yml
@@ -1,163 +1,63 @@
 name: Release test Workflow
 
 on:
-  # Triggers the workflow on push events
-  push:
-    branches:
-      - development
-  # Triggers the workflow on pull request events
-  pull_request:
+  # Triggers the workflow after the Test Workflow has completed
+  # workflow_run:
+  #   workflows: ['Test Workflow']
+  #   types:
+  #     - completed
+  #   branches:
+  #     - 'release/*'
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-concurrency:
-  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
-  cancel-in-progress: true
-
-env:
-  GITHUB_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
-  IS_DEV: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/development' }}
-
 jobs:
-  test-format:
+  release:
     runs-on: ubuntu-latest
+    if: ${{ github.event.workflow_run && github.event.workflow_run.conclusion == 'success' || true }}
+    environment: 'Release NPM'
+    env:
+      GH_TOKEN: ${{ secrets.GH_TOKEN }}
+      GIT_USER: ${{ vars.GIT_USER }}
+      GIT_EMAIL: ${{ vars.GIT_EMAIL }}
+      RELEASE_BRANCH: ${{ github.event.workflow_run.head_branch || github.ref }}
     steps:
+      - uses: actions/setup-node@v3
+        with:
+          node-version: 18
       - uses: actions/checkout@v3
         with:
-          ref: ${{ env.GITHUB_REF }}
           fetch-depth: 0
+          token: ${{ env.GH_TOKEN }}
+          ref: ${{ env.RELEASE_BRANCH }}
           submodules: recursive
-      - uses: ./.github/actions/init
-      - name: Format
-        run: npx nx format:check --verbose
-  test-lint:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
+      - uses: actions/cache@v3
         with:
-          ref: ${{ env.GITHUB_REF }}
-          fetch-depth: 0
-          submodules: recursive
-      - uses: ./.github/actions/init
-      - name: Lint
-        uses: ./.github/actions/run-optimal
-        with:
-          cmd: npx nx run-many --target=lint --all --parallel=2
-          affectedCmd: npx nx affected:lint
-          isDev: ${{ env.IS_DEV }}
-  test-stylelint:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          ref: ${{ env.GITHUB_REF }}
-          fetch-depth: 0
-          submodules: recursive
-      - uses: ./.github/actions/init
-      - name: Style Lint All
-        uses: ./.github/actions/run-optimal
-        with:
-          cmd: npx nx run-many --target=stylelint --all --parallel=2
-          affectedCmd: npx nx affected --target=stylelint
-          isDev: ${{ env.IS_DEV }}
-  test-tsconfig:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          ref: ${{ env.GITHUB_REF }}
-          fetch-depth: 0
-          submodules: recursive
-      - uses: ./.github/actions/init
-      - name: TsConfig Paths
-        uses: ./.github/actions/run-optimal
-        with:
-          cmd: npx nx run-many --target=paths --all --parallel=2
-          affectedCmd: npx nx affected --target=paths
-          isDev: ${{ env.IS_DEV }}
-  test-unit:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          ref: ${{ env.GITHUB_REF }}
-          fetch-depth: 0
-          submodules: recursive
-      - uses: ./.github/actions/init
-      - name: Unit Tests
-        uses: ./.github/actions/run-optimal
-        with:
-          cmd: |
-            npx nx run-many --target=test --all --parallel=2
-            node tools/coverage-reports/create-merged-layer-coverage-report.js libs/base
-            node tools/coverage-reports/create-merged-layer-coverage-report.js libs/domain
-            node tools/coverage-reports/create-merged-layer-coverage-report.js libs/platform
-          affectedCmd: npx nx affected:test
-          isDev: ${{ env.IS_DEV }}
-  test-visual-pr:
-    if: ${{ github.actor != 'dependabot[bot]' && github.event_name == 'pull_request' }}
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          ref: ${{ github.event.pull_request.head.sha }}
-          fetch-depth: 0
-          submodules: recursive
-      - uses: ./.github/actions/init
-      - name: Visual Regression Tests
-        env:
-          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
-          CHROMATIC_SHA: ${{ github.event.pull_request.head.sha }}
-          CHROMATIC_BRANCH: ${{ github.event.pull_request.head.ref }}
-        run: npx nx affected --target=visual-regression-pr
-  test-visual-dev:
-    if: ${{ github.event_name == 'push' }}
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          ref: ${{ env.GITHUB_REF }}
-          fetch-depth: 0
-          submodules: recursive
-      - uses: ./.github/actions/init
-      - name: Visual Regression Tests
-        env:
-          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
-          CHROMATIC_SHA: ${{ github.event.after }}
-          CHROMATIC_BRANCH: development
-        run: npx nx run storybook:visual-regression-branch
-  test-e2e-storefront:
-    if: ${{ github.actor != 'dependabot[bot]' }}
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          ref: ${{ env.GITHUB_REF }}
-          fetch-depth: 0
-          submodules: recursive
-      - uses: ./.github/actions/init
-      - name: Storefront E2E Tests
-        uses: ./.github/actions/run-optimal
-        env:
-          SCOS_BASE_URL: ${{ secrets.SCOS_BASE_URL }}
-          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
-          STORE: DE
-        with:
-          cmd: npm run sf:e2e:headless:ci
-          affectedCmd: npm run sf:e2e:headless:ci:affected
-          isDev: ${{ env.IS_DEV }}
-  test-build:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          ref: ${{ env.GITHUB_REF }}
-          fetch-depth: 0
-          submodules: recursive
-      - uses: ./.github/actions/init
-      - name: Build
-        uses: ./.github/actions/run-optimal
-        with:
-          cmd: npx nx run-many --target=build --all --parallel=2
-          affectedCmd: npx nx affected:build
-          isDev: ${{ env.IS_DEV }}
+          path: ~/.npm
+          key: npm-node-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            npm-node-
+      - name: Auth Git
+        run: |
+          git config user.email "${{ env.GIT_EMAIL }}"
+          git config user.name "${{ env.GIT_USER }}"
+      - name: Install Deps
+        run: npm ci
+      - name: Build packages
+        run: npx nx run-many --target=build --all --parallel=2
+      - name: Fix js extension
+        run: node tools/post-build/add-js-extension.js
+      - name: Install verdaccio
+        run: npm i verdaccio
+      - name: Run verdaccio
+        run: verdaccio
+      - name: Set npm registry for @spryker-oryx to verdaccio
+        run: npm config set @spryker-oryx:registry http://localhost:4873
+
+
+#      - name: Release from packages
+#        if: ${{ startsWith(env.RELEASE_BRANCH, 'refs/heads/release/') }}
+#        run: npm run release-from-packages
+#      - name: Release Error Log
+#        if: failure()
+#        run: cat libs/lerna-debug.log
